### ISSUE TITLE
Add a unit test for the API

### ISSUE THREAD

**Issue by elthran** [elthran/UDK#10]
It should be very simple. It just checks
`http://localhost:5000/api/counties/1` 
`http://localhost:5000/api/users/1` 
and makes sure they return a county and user object. That way I can mess with the models and ensure that I'm still sending the front end the same data

**Comment by klondikemarlen** [comment]
Considering full suite with the following, but going for a basic pytest (https://flask.palletsprojects.com/en/1.1.x/testing/) for now.
```
# Pipenv
[dev-packages]
pytest = "*"
pytest-cov = "*"
pytest-flake8 = "*"
pytest-testmon = "*"
pytest-xdist = "*"
pytest-watch = "*"
pytest-spec = "*"
pytest-mock = "*"
```

```bash
# dev
test () {
  ptw --runner "python -m pytest --testmon --spec"
}
```
